name: Deploy to Azure

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Build app
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "petcalendar"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C593304CBB1546E7B5005466081ED3BB }}
          package: "./dist"
